print("##############################\n")
print("#                            #\n")
print("#    Muhammad Rizky Akbar    #\n")
print("#       2410817210016        #\n")
print("#                            #\n")
print("##############################\n")