nama = input("Nama                    : ")
NIM = input("NIM                     : ")
KP = input("Kelas Paralel           : ")
TTL= input("Tempat/Tanggal Lahir    : ")
Alamat = input("Alamat                  : ")
hobby = input("Hobby                   : ")
NHP= input("No. HP                  : ")

print(f"Nama                    : {nama}")
print(f"NIM                     : {NIM}")
print(f"Kelas Paralel           : {KP}")
print(f"Tempat/Tanggal Lahir    : {TTL}")
print(f"Alamat                  : {Alamat}")
print(f"Hobby                   : {hobby}")
print(f"No. HP                  : {NHP}")